### ISSUE TITLE
EntryCell cannot unfocus

### ISSUE THREAD

**Issue by RidhwanDev** [muak/AiForms.SettingsView#59]
Hello,

Great work, this is amazing. I just have an issue with the EntryCell... I cannot unfocus by clicking away from the keyboard? This is specially problematic with a numeric keyboard which doesn't even have a return key. The return key allows me to unfocus but otherwise I can't.

Thanks
Ridhwan

**Comment by muak** [comment]
@RidhwanDev 
Thank you for your report. 
And I'm sorry for the delay in my reply.

I knew your issue since before, but I have no good idea.
As an idea, there is that tapping other areas will be hidden a keyboard.
But this has an impact on other parts of the code.

I will think more about it. 

Thanks.
