### ISSUE TITLE
PickerCell does not support AppShell

### ISSUE THREAD

**Issue by ivoryguard** [muak/AiForms.SettingsView#67]
Hello.

I found an issue that Pressing PickerCell makes NullReferenceException with AppShell.
I suspect that currernt version of PickerCell may require NavigationPage as a MainPage.

Please, add AppShell support.

Best regards.

**Comment by bytefish** [comment]
Well, the problem seems to be in the "NavDelegate", which tries to set the Visibility of the Navigation Bar. Along these lines:

* https://github.com/xamarin/Xamarin.Forms/blob/3a22872d7002c8807c22e1ca2f50ad88d3026290/Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRenderer.cs#L482

I tried to read through the Xamarin.Forms Shell implementation, but I gave up. Here is what I did as a "fix", just to get it working for a Demo tommorow.

I implemented a very rudimentary UINavigationControllerDelegate, that does almost nothing:

```csharp
class NavDelegate : UINavigationControllerDelegate
{
    readonly ShellSectionRenderer _self;

    public NavDelegate(ShellSectionRenderer renderer)
    {
        _self = renderer;
    }

    public override void DidShowViewController(UINavigationController navigationController, [Transient] UIViewController viewController, bool animated)
    {
    }

    public override void WillShowViewController(UINavigationController navigationController, [Transient] UIViewController viewController, bool animated)
    {
        navigationController.SetNavigationBarHidden(false, true);
    }
}
```

Now I added some code in the PickerCellRenderer :

* https://github.com/muak/AiForms.SettingsView/blob/master/SettingsView.iOS/Cells/PickerCellRenderer.cs#L84

First casting the NavigationControll to the ShellSectionRenderer and then setting the Delegate to the stipped down version, that doesn't include the original problematic code:

```csharp
        /// <summary>
        /// Rows the selected.
        /// </summary>
        /// <param name="tableView">Table view.</param>
        /// <param name="indexPath">Index path.</param>
        public override void RowSelected(UITableView tableView, NSIndexPath indexPath)
        {
            if(_PickerCell.ItemsSource == null)
            {
                tableView.DeselectRow(indexPath, true);
                return;
            }

            var naviCtrl = (ShellSectionRenderer) GetUINavigationController(UIApplication.SharedApplication.KeyWindow.RootViewController);
            naviCtrl.Delegate = new NavDelegate(naviCtrl);

            _pickerVC = new PickerTableViewController(this, tableView);
            
            naviCtrl.PushViewController(_pickerVC, false);

            if (!_PickerCell.KeepSelectedUntilBack) 
            {
                tableView.DeselectRow(indexPath, true);
            }
        }
```

This makes it at least work with the Xamarin.Forms 4.0 Shell. But I honestly didn't understand the underlying problem yet, and just used the most straightforward way.

**Comment by ivoryguard** [comment]
How about using a popup for selecting like your android implementation, instead of current implemetation based on Navigation? It will make all platform rendering same and I think that control look&feel must be same on each platform.

In addition, picker cell for single selection only may be required. Text Picker Cell is not suitable to bind complex objects because of lack of DisplayPath and so on.

So, I had to add SelectedItems property and some extra code to link SelectedItems into SelectedItem in my ViewModel.

Best regards.

**Comment by muak** [comment]
@ivoryguard 
@bytefish 

Thank you for your report.

I tried to resolve with @bytefish 's way.
But the replaced delegate couldn't be restored.

For now, this issue can't be resolved.

**Comment by bytefish** [comment]
@muak Yes, sadly I also gave up. The problem is somewhere in Xamarin.Forms Shell internals. I switched back to just displaying modal Pages with Checkbox Lists for a Multipicker and use a Xamarin.Forms TableView, that opens the modal on a command.

**Comment by jpveldtman** [comment]
Hi @bytefish 
Since XF4.3.0.947036 I am getting exception "Nav Stack consistency error",
I can see it was changed,
`void IShellSectionController.SendPopping(Page page)
		{
			if (_navStack.Count <= 1)
				throw new Exception("Nav Stack consistency error");
			_navStack.Remove(page);
			SendAppearanceChanged();
		}`

Looking at the pickercell in this solution it is calling
`void DoPickToClose()
        {
            if (_pickerCell.UsePickToClose && _selectedCache.Count == _pickerCell.MaxSelectedNumber)
            {
                this.NavigationController.PopViewController(true);
            }
        }`
Anyone know how i can get past this issue not to restrict my Xamarin Forms version?

**Comment by cixonline** [comment]
This is something that probably really needs a fix given how much AppShell is being used. Until then, it may be worth detecting and blocking the use of PickerCell on iOS with AppShell until there is a fix to avoid further confusion.

For now, I've had to abandon SettingsView in our code and will look for alternative ways to implement iOS style settings.

**Comment by muak** [comment]
@ivoryguard
@bytefish
@jpveldtman 

Thank you for waiting.

The AppShell issue is solved.
Please wait for the next release.

Thanks for a lot of information.
